[Machine]
cpu_family = pentium2_klamath
cpu_multi = 1.5
cpu_speed = 100000000
cpu_use_dynarec = 1
fpu_type = internal
machine = m729
mem_size = 32768

[CPU]
cpu_family = pentium_p54c
cpu_speed = 75000000
cpu_multi = 1.5
fpu_type = internal

[Memory]
mem_size = 32768

[Video]
gfxcard = virge357_pci

[Input devices]
keyboard_type = keyboard_ps2
mouse_type = ps2

[Floppy and CD-ROM drives]
fdd_01_fn = ../../Build/Platform/PC/Quantum-DR0-PC-IA32.img
fdd_01_type = 35_2hd
fdd_02_fn = ../../Build/Platform/PC/Quantum-DR0-PC-IA32-Binaries.img
fdd_02_image_history_01 = ../../Build/Platform/PC/Quantum-DR0-PC-IA32-Binaries.img
fdd_02_type = 35_2hd

[General]
host_cpu = Intel(R) Core(TM) Ultra 9 275HX
uuid = e81bee57-fdf3-5ad5-8d11-014cc7816e8f
vid_renderer = qt_software
