
Welcome, and thank you for trying out QuantumOS!

You are running a VERY early version of QuantumOS. It is, quite literally, still
a baby. Expect instability -- likely (definetly) a lot of it on real hardware.

That being said, please report any and all issues on GitHub:
https://github.com/The-Quantum-Software-Project/Quantumissues

If you are testing on real hardware right now, HUGE thank you. Your feedback
is VITAL in order to make QuantumOS better.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See "System/License.md" for more details (can be read
using the "cat" command).

- The Quantum Software Project

P.S. -- "cat System/Credits.txt"!

