/**
 * @file Include/Quantum/Version.hpp
 * @brief Defines QuantumOS version macros.
 * @author Brandon Belna (<bbelna@aol.com>)
 * @copyright
 *   Copyright © 2025-2026 The Quantum Software Project. All rights reserved.
 *   Licensed under the GNU General Public License v2.0-only. See LICENSE.md
 *   for details.
 *
 * Generated by Toolchain/Build.sh - do not edit manually.
 */

#pragma once

/**
 * @brief The QuantumOS revision number.
 */
#define QUANTUMOS_REVISION 1

/**
 * @brief The QuantumOS version.
 */
#define QUANTUMOS_VERSION "DR0"

/**
 * @brief The QuantumOS release variant.
 */
#define QUANTUMOS_VERSION_VARIANT ""

/**
 * @brief The full QuantumOS release string, including version and variant.
 */
#define QUANTUMOS_RELEASE \
  QUANTUMOS_VERSION "" QUANTUMOS_VERSION_VARIANT

/**
 * @brief The date the release was built.
 */
#define QUANTUMOS_RELEASE_DATE __DATE__

/**
 * @brief The time the release was built.
 */
#define QUANTUMOS_RELEASE_TIME __TIME__

/**
 * @brief The target architecture.
 */
#if defined(ARCH_IA32)
  #define QUANTUMOS_ARCH "IA32"
#else
  #define QUANTUMOS_ARCH "Unknown"
#endif

/**
 * @brief The target platform.
 */
#if defined(PLATFORM_PC)
  #define QUANTUMOS_PLATFORM "PC"
#else
  #define QUANTUMOS_PLATFORM "Unknown"
#endif
