#!/bin/bash

echo "
Build.sh: Quantum Build Toolchain for Linux
Copyright (C) 2025-2026 The Quantum Software Project
Originally authored by Brandon Belna (<bbelna@aol.com>)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See LICENSE.md for more
details.
"

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Defaults ---

PLATFORM="PC"
ARCH="IA32"
MEDIA="HDD"
VERSION="DR0"
VARIANT=""
CLEAN=1
EMULATOR=""
SKIP_DOXYGEN=0
MAKE_VARS=""

# --- Parse arguments ---

for arg in "$@"; do
  case $arg in
    --platform=*) PLATFORM="${arg#*=}" ;;
    --arch=*)     ARCH="${arg#*=}" ;;
    --media=*)    MEDIA="${arg#*=}" ;;
    --version=*)  VERSION="${arg#*=}" ;;
    --variant=*)  VARIANT="${arg#*=}" ;;
    --clean|-c)   CLEAN=1 ;;
    --tests)      MAKE_VARS="$MAKE_VARS EXTRA_CFLAGS32='-DKERNEL_TESTS'" ;;
    --qemu)       EMULATOR="qemu" ;;
    --bochs)      EMULATOR="bochs" ;;
    --86box)      EMULATOR="86box" ;;
    --skip-doxygen|-sd) SKIP_DOXYGEN=1 ;;
    *)
      echo "Unknown argument: $arg"
      echo ""
      echo "Usage: Build.sh [options]"
      echo "  --platform=X    Target platform (default: PC)"
      echo "  --arch=X        Target architecture (default: IA32)"
      echo "  --media=X       Boot medium (default: Floppy)"
      echo "  --version=X     Version string (default: DR0)"
      echo "  --variant=X     Version variant, e.g. Alpha (default: empty)"
      echo "  --clean, -c     Clean before building"
      echo "  --tests         Build with kernel test support"
      echo "  --qemu          Launch QEMU after build"
      echo "  --bochs         Launch Bochs after build"
      echo "  --86box         Launch 86Box after build"
      echo "  --skip-doxygen  Skip documentation generation"
      exit 1
      ;;
  esac
done

cd "$REPO_ROOT"

echo ">>> BUILD Quantum ($PLATFORM/$ARCH, $VERSION$VARIANT) <<<"

# --- Generate Version.hpp ---

VERSION_HPP="$REPO_ROOT/Include/Quantum/Version.hpp"
VERSION_HPP_TMP=$(mktemp)
trap "rm -f $VERSION_HPP_TMP" EXIT

cat > "$VERSION_HPP_TMP" << VEOF
/**
 * @file Include/Quantum/Version.hpp
 * @brief Defines QuantumOS version macros.
 * @author Brandon Belna (<bbelna@aol.com>)
 * @copyright
 *   Copyright © 2025-2026 The Quantum Software Project. All rights reserved.
 *   Licensed under the GNU General Public License v2.0-only. See LICENSE.md
 *   for details.
 *
 * Generated by Toolchain/Build.sh - do not edit manually.
 */

#pragma once

/**
 * @brief The QuantumOS revision number.
 */
#define QUANTUMOS_REVISION 1

/**
 * @brief The QuantumOS version.
 */
#define QUANTUMOS_VERSION "$VERSION"

/**
 * @brief The QuantumOS release variant.
 */
#define QUANTUMOS_VERSION_VARIANT "$VERSION_VARIANT"

/**
 * @brief The full QuantumOS release string, including version and variant.
 */
#define QUANTUMOS_RELEASE \\
  QUANTUMOS_VERSION "" QUANTUMOS_VERSION_VARIANT

/**
 * @brief The date the release was built.
 */
#define QUANTUMOS_RELEASE_DATE __DATE__

/**
 * @brief The time the release was built.
 */
#define QUANTUMOS_RELEASE_TIME __TIME__

/**
 * @brief The target architecture.
 */
#if defined(ARCH_IA32)
  #define QUANTUMOS_ARCH "IA32"
#else
  #define QUANTUMOS_ARCH "Unknown"
#endif

/**
 * @brief The target platform.
 */
#if defined(PLATFORM_PC)
  #define QUANTUMOS_PLATFORM "PC"
#else
  #define QUANTUMOS_PLATFORM "Unknown"
#endif
VEOF

if ! cmp -s "$VERSION_HPP_TMP" "$VERSION_HPP"; then
  cp "$VERSION_HPP_TMP" "$VERSION_HPP"
  echo "  Generated $VERSION_HPP"
fi

# --- Clean ---

if [ $CLEAN -eq 1 ]; then
  make clean PLATFORM="$PLATFORM" ARCH="$ARCH"
fi

# --- Build ---

# Build all packages, generating compile_commands.json via bear.
# Clean builds overwrite; incremental builds append to the existing file.
if command -v bear &>/dev/null; then
  BEAR_ARGS="--output $REPO_ROOT/compile_commands.json"
  if [ $CLEAN -eq 0 ] && [ -f "$REPO_ROOT/compile_commands.json" ]; then
    BEAR_ARGS="$BEAR_ARGS --append"
  fi
  bear $BEAR_ARGS -- make -s all PLATFORM="$PLATFORM" ARCH="$ARCH" $MAKE_VARS
else
  echo "Warning: bear not installed, skipping compile_commands.json generation"
  echo "  Arch:   sudo pacman -S bear"
  echo "  Debian: sudo apt install bear"
  echo "  Fedora: sudo dnf install bear"
  make -s all PLATFORM="$PLATFORM" ARCH="$ARCH" $MAKE_VARS
fi

# --- Doxygen ---

if [ $SKIP_DOXYGEN -eq 0 ]; then
  echo ">>> BUILD Quantum.Doxygen <<<"
  mkdir -p Build/Documentation
  doxygen
  echo ">>> BUILD Quantum.Doxygen OK <<<"
else
  echo "Passed --skip-doxygen, skipping documentation generation"
fi

echo ">>> BUILD Quantum OK <<<"
echo "------------------------------------------------------------------------------------"

# --- Emulator ---

if [ -n "$EMULATOR" ]; then
  # Create the platform image before launching
  IMAGE_SCRIPT="$SCRIPT_DIR/Platform/$PLATFORM/Build${PLATFORM}${ARCH}${MEDIA}.sh"
  if [ -f "$IMAGE_SCRIPT" ]; then
    echo ">>> IMAGE $PLATFORM/$ARCH/$MEDIA <<<"
    bash "$IMAGE_SCRIPT" --version="$VERSION" --variant="$VARIANT"
  else
    echo "Error: No image script found at $IMAGE_SCRIPT"
    exit 1
  fi

  "$SCRIPT_DIR/VMs/Debug.sh" "$EMULATOR" "$PLATFORM" "$ARCH" "$VERSION" "$VARIANT" "$MEDIA"
fi
